// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgIzIspYlgMHNyR2lw5BxyDIdaiWH9OsY',
    appId: '1:160197640355:web:b3899ed71484df8c43bf16',
    messagingSenderId: '160197640355',
    projectId: 'stock-management-de0b8',
    authDomain: 'stock-management-de0b8.firebaseapp.com',
    storageBucket: 'stock-management-de0b8.appspot.com',
    measurementId: 'G-2METCQHN4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlkcr0FSgaY2YgKpOQ9N98ZGRNTpF9kEI',
    appId: '1:160197640355:android:c7932d260f02abb143bf16',
    messagingSenderId: '160197640355',
    projectId: 'stock-management-de0b8',
    storageBucket: 'stock-management-de0b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMKcT-DBxDtQ2dyNWgwSVs57ilAx-7VOI',
    appId: '1:160197640355:ios:2cfd9a3517fed08543bf16',
    messagingSenderId: '160197640355',
    projectId: 'stock-management-de0b8',
    storageBucket: 'stock-management-de0b8.appspot.com',
    iosClientId: '160197640355-39lqdqn8u0nldm2h5odu2u0rqhodu4gv.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockManagement',
  );
}
